# Codecov configuration
# https://docs.codecov.com/docs/codecov-yaml

coverage:
  precision: 2
  round: down
  range: "60...100"

  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: false
    patch:
      default:
        target: 80%
        threshold: 5%

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes

ignore:
  - "tests/**/*"
  - "benches/**/*"
  - "examples/**/*"
  - "src/python.rs"
  - "src/wasm.rs"
  - "src/uniffi_bindings.rs"
  - "src/tui.rs"
  - "src/main.rs"

flags:
  unittests:
    paths:
      - src/
    carryforward: true
