//! Experimental modules — APIs may change without notice.

#[cfg(feature = "experimental")]
pub mod adaptive_index;
#[cfg(feature = "experimental")]
pub mod adaptive_runtime;
#[cfg(feature = "experimental")]
pub mod agentic_memory;
#[cfg(feature = "experimental")]
pub mod analytics;
#[cfg(feature = "experimental")]
pub mod cloud_control;
pub mod clustering;
#[cfg(feature = "experimental")]
pub mod crdt;
pub mod dedup;
#[cfg(feature = "experimental")]
pub mod distributed_hnsw;
#[cfg(feature = "experimental")]
pub mod edge_optimized;
#[cfg(feature = "experimental")]
pub mod edge_partitioning;
#[cfg(feature = "experimental")]
pub mod edge_runtime;
pub mod gpu;
pub mod graph;
#[cfg(feature = "experimental")]
pub mod graphrag_index;
#[cfg(feature = "experimental")]
pub mod knowledge_graph;
#[cfg(feature = "experimental")]
pub mod learned_tuning;
#[cfg(feature = "experimental")]
pub mod llm_cache;
#[cfg(feature = "experimental")]
pub mod optimizer;
#[cfg(feature = "experimental")]
pub mod platform_adapters;
#[cfg(feature = "experimental")]
pub mod playground;
pub mod plugin;
#[cfg(feature = "experimental")]
pub mod plugin_registry;
#[cfg(feature = "experimental")]
pub mod python_arrow;
#[cfg(feature = "experimental")]
pub mod rebalance;
#[cfg(feature = "experimental")]
pub mod serverless_runtime;
#[cfg(feature = "experimental")]
pub mod streaming_upsert;
pub mod temporal;
#[cfg(feature = "experimental")]
pub mod vector_streaming;
#[cfg(feature = "experimental")]
pub mod zero_copy;
